import { Prisma, PayloadMeta } from '@prisma/client';

export interface ApiTokenEntity {
  id: string; // UUID - auto generated by Prisma
  tenantId: string; // foreign key to Tenant entity
  name: string; // e.g. 'api-v1', 'admin-dashboard'
  scopes: Array<string>;
  expiresAt: Date | null; // null = no expiration
  isActive: boolean; // default true

  // Prisma generated fields
  createdAt?: Date;
  updatedAt?: Date;
  deletedAt?: Date;
}

export interface ApiTokenPayload {
  tenantId: string;
  iat: number;
  exp: number;
  scopes?: Array<string>;
  [key: string]: unknown;
}

export type TokenClaims = PayloadMeta<ApiTokenEntity, ApiTokenPayload>;